// Verifies the redesigned Forgot Password flow for vendor, couple, and
// admin: wrong contact info is rejected, correct contact info triggers a
// REAL Firebase password-reset email (checked via the Auth emulator's own
// captured-email API, not just trusting the UI's success message).
const { chromium } = require('playwright');

const BASE = 'http://localhost:8000';
const AUTH_EMULATOR = 'http://localhost:9099';
const PROJECT_ID = 'demo-forever-begins';

function fail(msg) { console.log('FAIL: ' + msg); process.exitCode = 1; }
function ok(cond, msg) { if (cond) console.log('ok: ' + msg); else fail(msg); }

async function getOobCodesFor(email) {
  const res = await fetch(`${AUTH_EMULATOR}/emulator/v1/projects/${PROJECT_ID}/oobCodes`);
  const json = await res.json();
  return (json.oobCodes || []).filter(c => c.email === email && c.requestType === 'PASSWORD_RESET');
}

(async () => {
  const browser = await chromium.launch();

  console.log('=== VENDOR FORGOT PASSWORD ===');
  const page = await browser.newPage();
  const errors = [];
  page.on('console', msg => { if (msg.type() === 'error') errors.push(msg.text()); });

  const username = `pw_forgot_test_${Date.now()}`;
  const email = `${username}@example.com`;
  await page.goto(`${BASE}/index.html`);
  const donationClose = page.locator('#donationCloseBtn');
  await donationClose.waitFor({ state: 'visible', timeout: 5000 }).catch(() => {});
  if (await donationClose.isVisible().catch(() => false)) await donationClose.click();
  await page.locator('#vBusinessName').fill('Forgot Password Test Venue');
  await page.locator('#vCategory').selectOption('Wedding Venues');
  await page.locator('#vUsername').fill(username);
  await page.locator('#vPassword').fill('OriginalPass123!');
  await page.locator('#vPhone').fill('+961 3 555 000');
  await page.locator('#vEmail').fill(email);
  await page.locator('#vLocation').fill('Beirut, Lebanon');
  await page.locator('input[name="plan"][value="Basic"]').check({ force: true });
  await page.locator('#vTransactionRef').fill('E2E-FORGOT-0001');
  await page.locator('#vendorForm button[type="submit"]').click();
  await page.waitForFunction(() => (document.getElementById('vendorNote') || {}).textContent?.trim().length > 0, { timeout: 15000 });
  ok(true, 'Vendor signed up');

  await page.goto(`${BASE}/vendor.html`);
  await page.locator('#vendorForgotPasswordLink').click();
  await page.locator('#vendorForgotUsername').fill(username);
  await page.locator('#vendorForgotContact').fill('wrong@nowhere.com');
  await page.locator('#vendorSendCodeBtn').click();
  await page.waitForFunction(() => (document.getElementById('vendorForgotNote1') || {}).textContent?.trim().length > 0, { timeout: 10000 });
  const wrongContactNote = await page.locator('#vendorForgotNote1').textContent();
  ok(/doesn't match/i.test(wrongContactNote), 'Wrong contact info correctly rejected: ' + wrongContactNote);

  await page.locator('#vendorForgotContact').fill(email);
  await page.locator('#vendorSendCodeBtn').click();
  await page.waitForFunction(() => (document.getElementById('vendorForgotNote1') || {}).textContent?.includes('reset link'), { timeout: 10000 });
  const successNote = await page.locator('#vendorForgotNote1').textContent();
  ok(successNote.includes(email), 'Correct contact triggers success message mentioning the real email: ' + successNote);

  const oobCodes = await getOobCodesFor(email);
  ok(oobCodes.length > 0, `A real password-reset email was actually generated by Firebase Auth for ${email} (found ${oobCodes.length} matching oobCode(s))`);

  console.log('\nConsole errors:', errors.length);
  errors.forEach(e => console.log(' -', e));
  ok(errors.length === 0, 'No console errors');

  console.log('\n=== ADMIN FORGOT PASSWORD ===');
  const adminPage = await browser.newPage();
  const adminErrors = [];
  adminPage.on('console', msg => { if (msg.type() === 'error') adminErrors.push(msg.text()); });
  await adminPage.goto(`${BASE}/admin.html`);
  await adminPage.locator('#adminForgotPasswordLink').click();
  await adminPage.locator('#adminForgotContact').fill('wrong@nowhere.com');
  await adminPage.locator('#adminSendCodeBtn').click();
  await adminPage.waitForFunction(() => (document.getElementById('adminForgotNote1') || {}).textContent?.trim().length > 0, { timeout: 10000 });
  const adminWrongNote = await adminPage.locator('#adminForgotNote1').textContent();
  ok(/doesn't match/i.test(adminWrongNote), 'Wrong admin contact info correctly rejected: ' + adminWrongNote);

  await adminPage.locator('#adminForgotContact').fill('hello@foreverbegins.pro');
  await adminPage.locator('#adminSendCodeBtn').click();
  await adminPage.waitForFunction(() => (document.getElementById('adminForgotNote1') || {}).textContent?.includes('reset link'), { timeout: 10000 });
  const adminSuccessNote = await adminPage.locator('#adminForgotNote1').textContent();
  ok(adminSuccessNote.includes('hello@foreverbegins.pro'), 'Correct admin contact triggers success message: ' + adminSuccessNote);

  const adminOobCodes = await getOobCodesFor('hello@foreverbegins.pro');
  ok(adminOobCodes.length > 0, `A real password-reset email was actually generated for the admin account (found ${adminOobCodes.length} matching oobCode(s))`);

  console.log('\nAdmin page console errors:', adminErrors.length);
  adminErrors.forEach(e => console.log(' -', e));
  ok(adminErrors.length === 0, 'No console errors on the admin page');

  console.log('\n=== COUPLE FORGOT PASSWORD ===');
  const couplePage = await browser.newPage();
  const coupleErrors = [];
  couplePage.on('console', msg => { if (msg.type() === 'error') coupleErrors.push(msg.text()); });
  const coupleUsername = `pw_couple_forgot_${Date.now()}`;
  const coupleEmail = `${coupleUsername}@example.com`;
  await couplePage.goto(`${BASE}/index.html#planning`);
  const coupleDonationClose = couplePage.locator('#donationCloseBtn');
  await coupleDonationClose.waitFor({ state: 'visible', timeout: 5000 }).catch(() => {});
  if (await coupleDonationClose.isVisible().catch(() => false)) await coupleDonationClose.click();
  const signupToggle = couplePage.locator('a, button', { hasText: /sign up/i }).first();
  if (await signupToggle.isVisible().catch(() => false)) await signupToggle.click();
  await couplePage.locator('#signupUsername').fill(coupleUsername);
  await couplePage.locator('#signupPassword').fill('OriginalPass123!');
  await couplePage.locator('#signupBride').fill('Forgot Bride');
  await couplePage.locator('#signupGroom').fill('Forgot Groom');
  await couplePage.locator('#signupEmail').fill(coupleEmail);
  await couplePage.locator('#signupPhone').fill('+961 3 666 000');
  await couplePage.locator('#signupForm button[type="submit"]').click();
  await couplePage.waitForFunction(() => !document.getElementById('dashboard').classList.contains('hidden'), { timeout: 15000 });
  await couplePage.locator('#logoutBtn').click();
  await couplePage.waitForFunction(() => !document.getElementById('authWrapper').classList.contains('hidden'), { timeout: 10000 });

  // "Forgot password?" only shows on the Login tab (not Signup) — switch
  // to it explicitly, since logging out doesn't reset which tab is active.
  const loginTab = couplePage.locator('[data-authtab="login"]');
  if (await loginTab.isVisible().catch(() => false)) await loginTab.click();

  await couplePage.locator('#coupleForgotPasswordLink').click();
  await couplePage.locator('#coupleForgotUsername').fill(coupleUsername);
  await couplePage.locator('#coupleForgotContact').fill('wrong@nowhere.com');
  await couplePage.locator('#coupleSendCodeBtn').click();
  await couplePage.waitForFunction(() => (document.getElementById('coupleForgotNote1') || {}).textContent?.trim().length > 0, { timeout: 10000 });
  const coupleWrongNote = await couplePage.locator('#coupleForgotNote1').textContent();
  ok(/doesn't match/i.test(coupleWrongNote), 'Wrong couple contact info correctly rejected: ' + coupleWrongNote);

  await couplePage.locator('#coupleForgotContact').fill(coupleEmail);
  await couplePage.locator('#coupleSendCodeBtn').click();
  await couplePage.waitForFunction(() => (document.getElementById('coupleForgotNote1') || {}).textContent?.includes('reset link'), { timeout: 10000 });
  const coupleSuccessNote = await couplePage.locator('#coupleForgotNote1').textContent();
  ok(coupleSuccessNote.includes(coupleEmail), 'Correct couple contact triggers success message: ' + coupleSuccessNote);

  const coupleOobCodes = await getOobCodesFor(coupleEmail);
  ok(coupleOobCodes.length > 0, `A real password-reset email was actually generated for the couple account (found ${coupleOobCodes.length} matching oobCode(s))`);

  console.log('\nCouple page console errors:', coupleErrors.length);
  coupleErrors.forEach(e => console.log(' -', e));
  ok(coupleErrors.length === 0, 'No console errors on the couple page');

  await browser.close();
  console.log('\n=== DONE ===');
  process.exit(process.exitCode ? 1 : 0);
})().catch(err => { console.error('FATAL:', err); process.exit(1); });
